{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "47303fcd",
   "metadata": {
    "_execution_state": "idle",
    "_uuid": "051d70d956493feee0c6d64651c6a088724dca2a",
    "papermill": {
     "duration": 0.003527,
     "end_time": "2022-05-29T04:12:54.894594",
     "exception": false,
     "start_time": "2022-05-29T04:12:54.891067",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "---\n",
    "title: \"BellaBeat Behavior Analysis\"\n",
    "author: \"Durga Devi Sundaram\"\n",
    "output:\n",
    "  html_document: default\n",
    "  pdf_document: default\n",
    "---\n",
    "\n",
    "## Introduction and background\n",
    "This R Markdown document sums up my user behavior analysis to help guide BellaBeat Marketing team to strategize on \n",
    "targeting the right consumer segment to boost their sales for one of their product, the smart watch called **Time**\n",
    "\n",
    "\n",
    "## Source file details\n",
    "I am using the following open source dataset in the form of CSV files that can be found at the link below:\n",
    "https://www.kaggle.com/arashnic/fitbit\n",
    "* Attention: Although I find that the dataset is not ROCCC compliant, I am going ahead with the analysis for practice purposes. I intend to get the right dataset and provide advanced analysis at a later time. Stay tuned!\n",
    "\n",
    "The user fitness details being tracked by the FitBit application and tracker are as follows:\n",
    "* Activity level \n",
    "* Step count\n",
    "* Distance \n",
    "* Sleep measurement: Time Asleep and Time on Bed\n",
    "* Calories burnt\n",
    "* Heartrate\n",
    "\n",
    "These CSV files can be categorized based on the following levels of granularity:\n",
    "* Daily\n",
    "* Hourly\n",
    "* Minutes\n",
    "* Seconds\n",
    "  \n",
    "For my analysis, I would like to rollup the daily data into week level. I feel the minutes level and seconds level information for \n",
    "different users is too fine to help my analysis.\n",
    "So I would be rolling up the minutes and seconds level to average it out to hourly data to find user behavior patterns.  \n",
    "\n",
    "## Installing and loading the necessary packages and libraries\n",
    "For our purpose, we are using the following packages in R: \n",
    "* tidyverse - Basic package for data analysis\n",
    "* lubridate - For date manipulation\n",
    "* skimr & janitor - For data cleaning\n",
    "* sqldf - For analysis using SQL commands on dataframe\n",
    "\n",
    "```{r}\n",
    "install.packages(\"tidyverse\")\n",
    "install.packages(\"lubridate\")\n",
    "install.packages(\"skimr\")\n",
    "install.packages(\"janitor\")\n",
    "install.packages(\"sqldf\")\n",
    "\n",
    "library(tidyverse)\n",
    "library(lubridate)\n",
    "library(skimr)\n",
    "library(janitor)\n",
    "library(dplyr)\n",
    "library(sqldf)\n",
    "```\n",
    "\n",
    "\n",
    "## Loading the source files into R structures\n",
    "For my analysis I used spreadsheets to analyse Daily and Hourly data.\n",
    "Minutes and Seconds level data are too huge to process in spreadsheets.\n",
    "They have format issues to be loaded into SQL as well. I leveraged R to cleanup the minute level METs data.\n",
    "I used R solely for analysing the seconds level data about heartrate.\n",
    "\n",
    "Let's dig in!\n",
    "\n",
    "## Cleaning the data \n",
    "I am fixing the date format for this dataset to datetime format and saving it into heartrate_df_clean dataframe.\n",
    "Finally, I am converting ID from number to string field help plot axis values in graph easily\n",
    "\n",
    "```{r}\n",
    "heartrate_df <- read_csv(\"heartrate_seconds_merged.csv\")\n",
    "colnames(heartrate_df)\n",
    "\n",
    "heartrate_df_clean <- mutate(heartrate_df, Time_date = mdy_hms(Time))\n",
    "head(heartrate_df_clean,4)\n",
    "\n",
    "heartrate_df_clean <- select(heartrate_df_clean, -Time)\n",
    "head(heartrate_df_clean,4)\n",
    "\n",
    "heartrate_df_clean <- mutate(heartrate_df_clean, Id = as.character(Id))\n",
    "\n",
    "skim_without_charts(heartrate_df_clean)\n",
    "```\n",
    "\n",
    "Once I check the summary statistics of the dataset, I proceed to check for data validity.\n",
    "I cross verify the user IDs to see if they match with the parent dataset dailyActivity_merged as available my spreadsheet.\n",
    "I loved experimenting the sql usage within the context of R using sqldf function.\n",
    "There are multiple ways to do this, which is the power of R!\n",
    "\n",
    "```{r}\n",
    "sqldf(\"select count(distinct(ID)) from heartrate_df_clean\")\n",
    "\n",
    "sqldf(\"select distinct(ID) from heartrate_df_clean\")\n",
    "\n",
    "n_distinct(heartrate_df_clean$Id)\n",
    "\n",
    "```\n",
    "\n",
    "## Housekeeping\n",
    "Given the dataset size, I proceed to cleanup the source dataframe to free up some memory for further analysis.\n",
    "\n",
    "```{r}\n",
    "rm(heartrate_df)\n",
    "```\n",
    "\n",
    "## Analysing the data\n",
    "\n",
    "#### Splitting the time \n",
    "Here I am splitting the time into individual components of year, month, day, weekday, hour, minute and seconds.\n",
    "I'm sure there will be an efficient way to process this, but for beginner level, I find this good enough.\n",
    "\n",
    "```{r}\n",
    "heartrate_df_clean <- mutate(heartrate_df_clean, Time_year = year(Time_date), Time_mon = month(Time_date), Time_dateNum = mday(Time_date), Time_week = wday(Time_date, label = TRUE), Time_hour = hour(Time_date), Time_min = minute(Time_date), Time_sec = second(Time_date))\n",
    "\n",
    "glimpse(heartrate_df_clean)\n",
    "```\n",
    "\n",
    "## Visualize data\n",
    "Now we are ready to summarize the average heartbeat by user, day, hour and so on.\n",
    "Heartbeat data gives a good indicator of the user's activity level. \n",
    "\n",
    "I am creating a scatterplot with different users to show average heartrate per hour of the day. \n",
    "\n",
    "```{r}\n",
    "heartrate_df_clean %>%\n",
    "  group_by(Id, Time_mon, Time_dateNum, Time_hour) %>%\n",
    "  summarise(AvgHeartRate = mean(Value)) %>%\n",
    "  ggplot(aes(x=Time_hour, y=AvgHeartRate, group = Id, color = Id)) + \n",
    "  geom_point() +\n",
    "  labs(x= \"Hour of the Day\", y= \"Average Heartrate\")\n",
    "```\n",
    "\n",
    "#### Analysis Result :\n",
    "\n",
    "This shows which user is more active and which one is less active by the hour of the day.\n",
    "After analysing the heartrate by users, we find the following:\n",
    "* Approximately 10-15% of the users are active with more than 140 bpm.\n",
    "* Those who are highly active during the later part of the day have a better quality of sleep signalled by lower heartrate below 60bpm.\n",
    "* Users who have recorded high intensity activity through heartrate of more than 120 bpm plan their workouts between noon and 6 PM, which is lunch break and right after office.\n",
    "\n",
    "Next I want to take the users as a whole and want to see the spread of heartrate across each day of the week.\n",
    "This will tell us which days are more intense for the sample set and which hours are more intense on an average.\n",
    "I do this by creating a heatmap as below.\n",
    "I want to save this image as a pdf for later reference.\n",
    "\n",
    "```{r}\n",
    "heartrate_df_clean %>%\n",
    "  group_by( Time_week, Time_hour) %>%\n",
    "  summarise(AvgHeartRate = mean(Value)) %>%\n",
    "  ggplot(aes(x=Time_hour, y=Time_week, fill=AvgHeartRate)) + \n",
    "  geom_tile() +\n",
    "  scale_fill_gradient(low=\"blue\", high=\"red\")+\n",
    "  scale_x_continuous(breaks = scales::pretty_breaks(n=23))+\n",
    "  labs(x = \"Hour\", y= \"Week\", \n",
    "       title=\"Heartrate vs Day of the week\", \n",
    "       subtitle =\"Average heartrate across different hours over various days of the week\",\n",
    "       fill = \"Average Heart Rate\")\n",
    "\t   \n",
    "ggsave(\"Heartrate_Weekday.pdf\", device = \"pdf\", width = 8, height = 10, units = \"in\" )\n",
    "\t   \n",
    "```\n",
    "#### Analysis Result :  \n",
    "\n",
    "* The heartrate heatmap shows that the average user in the sample set are early risers with lowest heartrate between 12 -5AM\n",
    "* Their week starts slowly with Sunday to Tuesday being lower activity as compared to the second half of the week.\n",
    "During the workweek, their favorite workout time is between 4-7PM \n",
    "* On Tuesdays, they seem to push the high intensity workout during lunch break.\n",
    "* On weekends they like to workout late on Friday between 5:30-8PM.\n",
    "* On Saturday, they wake up late by and workout during noon, probably before a brunch.\n",
    "* Sundays are relatively relaxed.\n",
    "\n",
    "## Conclusion\n",
    "Based on the analysis, the user group seems to be office goers with desk jobs. They are highly motivated and follow a set routine in their life.\n",
    "They are committed to wellness and have the discipline to workout through out the week.\n",
    "* To target the population with these characteristics, the marketing team could use *social media* as a preferred medium to reach out to the segment of population who are single and have more control over their lives and buffer to prioritize their needs. \n",
    "* The selling point can be stress management and better quality of sleep as shown by the data to motivate them to improve their physical fitness which contributes to their looking and feeling good.\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 3.753226,
   "end_time": "2022-05-29T04:12:55.018939",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2022-05-29T04:12:51.265713",
   "version": "2.3.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
